# nix-shell -p ssh-to-age
# ssh-keyscan host.phire.org | ssh-to-age
keys:
  - &admin_a age19fc4ty8uyhgtp5ywsn0mm33vl5g2kwk6c668hk3rewlct8zd7ujsuau5pu
  - &admin_yubi 476D3E0340F8443FC10984ABE361F31ADD2CEFF
  - &system_moloch age1cqzcnkrlap79dfywzg22qlsmyvswed04ljn6thjzh0ljpvwrjudqsq78ru
  - &system_ipos age1depmjeuv8lmjf82h5sl04h4em7dknvzxkrfwxek86q69kevyt45sjq8507
  - &system_stolas age14vfktvmkluy3ap083zrma403qgq0tfj0tj6fegkt6kd36h2fdagskyykyz
  - &system_orobas age1339vfu82ups8gwfyfcpktdr4mjh0yntun28k6edvkl6knv20jcgstag04t
  - &system_volac age1lqr6mfl4vhszqcpyd484dn3n6zm8x0y7x86hc05q3wp8ggy09ftsq40jvn
  - &system_malphas age1yduzg46r4ku8emq7frrlkl8d7saz4m542ctl8uf2snkfmj24q9gs07ps7v
  - &system_agares age1nrw095eqnu8rahneevg7kl4r6508qwmyhy40h03mmpqvz7h6k96s0kr5e2
  - &system_azazel age15g87upjl3hev580xmdtusmzgrngq5suqvdnn0h062epfrmlvgecsa5ksg2
# nix-shell -p sops --run "sops secrets/example.yaml"
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_a
        - *system_moloch
        - *system_ipos
        - *system_stolas
        - *system_orobas
        - *system_volac
        - *system_malphas
        - *system_agares
        - *system_azazel
  - path_regex: systems/ipos/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_a
        - *system_ipos
  - path_regex: systems/moloch/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_a
        - *system_moloch
  - path_regex: systems/stolas/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_a
        - *system_stolas
  - path_regex: systems/orobas/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_a
        - *system_orobas
  - path_regex: systems/volac/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_a
        - *system_volac
  - path_regex: systems/malphas/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_a
        - *system_malphas
  - path_regex: systems/agares/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_a
        - *system_agares
  - path_regex: systems/azazel/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *admin_a
        - *system_azazel
