#!/usr/bin/env bash

battery=/sys/class/power_supply/BAT0

full=$(cat $battery/energy_full)
now=$(cat $battery/energy_now)

pct=$(echo $now $full | awk '{ printf "%d\n", ($1 / $2) * 100 }')

echo $pct%
echo $pct%


