# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1e981e34-9fc3-4323-a511-555a5b4cc1c8";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E60A-6FB4";
      fsType = "vfat";
    };

  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-label/storage-unenc";
    fsType = "ext4";
    options = [ "noatime" ];
  };

  fileSystems."/mnt/enc" = {
    device = "UUID=0789211e-1c89-442a-8372-d66172a9fe0c";
    fsType = "ext4";
    options = [
      "noauto"
      "noatime"
#      "x-mount.mkdir"
      "x-systemd.requires=systemd-cryptsetup@storage_enc.service"
    ];
  };

  environment.etc.crypttab = {
    enable = true;
    text = ''
      storage_enc UUID=6d1c1ba4-62d5-4f46-a93a-e627fd186b35 none luks,noauto
    '';
  };

  environment.systemPackages = with pkgs; [
    cryptsetup
  ];

  swapDevices =
    [ { device = "/dev/disk/by-uuid/395b3c2e-8b3e-41f3-80cf-60a478f15b7d"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #;networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp114s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp60s0u1u4u3u3.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
